//! Generated gRPC bindings for the Sekai-Chisei wire types and the Tenkai-owned
//! graph-action and runtime v1 contracts.
//!
//! Sekai and Chisei messages are `sekai-proto` at commit
//! `67157d1fa242ac2f133c88243ef23b56f88042e6`. Tenkai-owned messages are
//! generated by `tenkai-wire` from `proto/tenkai/`. Legacy graph ActionTypeDef
//! RPCs were removed on that Sekai revision; remote Tenkai uses the governed
//! Action surface, while embedded hosts keep Tenkai-local graph-action
//! definitions.

pub use tenkai_wire::{chisei, graph_action, runtime_v1, sekai};
